services:
  db:
    image: postgres
    container_name: vehicle-rental-database
    environment:
      POSTGRES_DB: vehicle-rental
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
