spring:
  application:
    name: "vehicle-rental-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle-rental
    username: user
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

